name: Pull Request Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  pull_request_target:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "latest"

      - name: Login to GitHub Container Registry
        if: github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'push-to-ghcr')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: type=raw,value=pr-${{ github.event.number }}
          flavor: latest=false

      - name: Docker - Build and Push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'push-to-ghcr') }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Comment on Pull Request with Container Image URL
        if: success() && github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'push-to-ghcr')
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: Built and pushed Docker image for PR
          message: |
            The Docker image for this pull request has been built and pushed to GHCR.

            Image URL: `ghcr.io/${{ github.repository }}:pr-${{ github.event.number }}`
